### ISSUE TITLE
AWS or Azure?

### ISSUE THREAD

**Issue by felipeturing** [ssharong/ssharong-ops#1]
Hi! @turinesco. 

Which sass have you selected, AWS or Azure? and Why? 

I have had a lot of problems while I was working on Azure the last times, because I don't have the complete knowledge

 I hope you help me, thanks for reading me..

**Comment by turinesco** [comment]
Yeah, I use AWS because it's my favorite SASS for this project, because we can deploy machine learning models on gpu.
