### ISSUE TITLE
Falta documentación de módulo usuarios

### ISSUE THREAD

**Issue by turinesco** [ssharong/ssharong-ops#3]
Cuanto antes, hijo

**Comment by felipeturing** [comment]
De acuerdo, estoy en proceso de documentación ahora mismo. 

- Primero
**- Segundo** 
- Tercero 
`python3 -m pip install yolo`

Querido @turinesco espero haya comprendido lo que quiero decir. 
Este problema tiene mucho que ver con #1.

**Comment by felipeturing** [comment]
Además te paso una imagen para un mejor entendimiento amigo.[google.com](google)
![RLlib](https://user-images.githubusercontent.com/42989992/133564613-c8636849-be44-4d8d-bb84-022471bde76a.png)

**Comment by turinesco** [comment]
Genial gracias, ahora cerramos esta sección.
